apiVersion: v1
kind: Service
metadata:
  name: gradle-build-cache
spec:
  selector:
    app.kubernetes.io/component: build-cache-node
  ports:
  - name: http
    port: 5071
  - name: grpc-bazel
    port: 6011
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: build-cache-node
  labels:
    app.kubernetes.io/component: build-cache-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: build-cache-node
  serviceName: build-cache-node
  template:
    metadata:
      labels:
        app.kubernetes.io/component: build-cache-node
    spec:
      initContainers:
      - name: config-mounter
        image: "busybox:1.33.0"
        command: [
          "sh",
          "-ce",
          "cp /tmp/config.yaml /data/conf/config.yaml" ]
        volumeMounts:
        - name: tmp-build-cache-config-file
          mountPath: /tmp
        - name: build-cache-config-dir
          mountPath: /data/conf
      containers:
      - name: build-cache-node
        image: gradle/build-cache-node:21.2
        args: [ "start" ]
        ports:
        - name: http
          containerPort: 5071
        - name: grpc-bazel
          containerPort: 6011
        resources:
          requests:
            memory: 1Gi
            cpu: "500m"
          limits:
            memory: 2Gi
            cpu: "1000m"
        env:
        - name: EXCLUSIVE_VOLUME_SIZE
          value: "10Gi"
        volumeMounts:
        - name: build-cache-node-data-volume
          mountPath: /data
        - name: build-cache-config-dir
          mountPath: /data/conf
      volumes:
      - name: build-cache-config-dir
        emptyDir: {}
      - name: tmp-build-cache-config-file
        secret:
          secretName: gradle-build-cache-config-secret
  volumeClaimTemplates:
  - metadata:
      name: build-cache-node-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: '10Gi'